const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const { spawn } = require('node:child_process')
const { once } = require('node:events')

test('API completa con datos aislados', async t => {
  const root = __dirname
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'mascotas-test-'))
  await fs.cp(root, temp, { recursive: true, filter: src => !['node_modules', 'test'].includes(path.basename(src)) })
  const server = spawn(process.execPath, ['server.js'], { cwd: temp, env: { ...process.env, PORT: '0', NODE_PATH: path.join(root, 'node_modules') } })
  t.after(async () => { server.kill(); await once(server, 'exit'); await fs.rm(temp, { recursive: true, force: true }) })
  const port = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Servidor no inició')), 5000)
    let output = ''
    server.stdout.on('data', chunk => { output += chunk; const match = output.match(/PORT: (\d+)/); if (match) { clearTimeout(timeout); resolve(match[1]) } })
    server.once('error', reject)
  })
  const request = (url, method = 'GET', body) => fetch(`http://localhost:${port}${url}`, { method, headers: { 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) })
  assert.equal((await request('/')).status, 200)
  const info = await (await request('/info')).text()
  assert.match(info, /PATCH/)
  const initial = await (await request('/api/mascotas')).json()
  const created = await request('/api/mascotas', 'POST', { nombre: 'Prueba', tipo: 'Gato' })
  assert.equal(created.status, 201)
  const pet = await created.json()
  assert.deepEqual(await (await request(`/api/mascotas/${pet.id}`)).json(), pet)
  const updated = await (await request(`/api/mascotas/${pet.id}`, 'PATCH', { nombre: 'Editada' })).json()
  assert.equal(updated.nombre, 'Editada')
  assert.equal(updated.tipo, 'Gato')
  const persisted = JSON.parse(await fs.readFile(path.join(temp, 'data_mascotas.json'), 'utf8'))
  assert.equal(persisted.find(m => m.id === pet.id).nombre, 'Editada')
  assert.equal((await request('/api/mascotas', 'POST', {})).status, 400)
  assert.equal((await request(`/api/mascotas/${pet.id}`, 'DELETE')).status, 200)
  for (const method of ['GET', 'PATCH', 'DELETE']) assert.equal((await request(`/api/mascotas/${pet.id}`, method, method === 'PATCH' ? { nombre: 'Ausente' } : undefined)).status, 404)
  assert.deepEqual(await (await request('/api/mascotas')).json(), initial)
})
